### ISSUE TITLE
npm start之后，电脑风扇就狂转。

### ISSUE THREAD

**Issue by qq157788394** [progrape/router#1]
如题，下载下来，npm start之后，电脑风扇狂转，关闭了就好了。

**Comment by progrape** [comment]
这个不是什么问题吧，就算是，也算是 `node` 或者 `webpack` 的问题。

`npm start` 之后是调用 `webpack` 来编译和预览的

**Comment by qq157788394** [comment]
我不是很懂这个，weui npm start之后风扇就没这么狂转。

**Comment by progrape** [comment]
它们跑的程序不一样，消耗的资源也不一样，webpack 相对会更多一点
