### ISSUE TITLE
可以使用ajax页面吗？

### ISSUE THREAD

**Issue by wcj343169893** [progrape/router#11]
或者说是初始化的时候，获取页面上的ajax页面
 var toast = {
        url: '/toast',
        className: 'toast',
        render: function () {
            return getPage("/usercentertoast.html");
        },
        bind: function () {
            $('#container').on('click', '#showToast', function () {
                $('#toast').show();
                setTimeout(function () {
                    $('#toast').hide();
                }, 2000);
            }).on('click', '#showLoadingToast', function () {
                $('#loadingToast').show();
                setTimeout(function () {
                    $('#loadingToast').hide();
                }, 2000);
            });
        }
    };

**Comment by progrape** [comment]
已经可以异步请求数据然后渲染页面了~
