### ISSUE TITLE
请问render能直接return一个URL吗？

### ISSUE THREAD

**Issue by zx8887** [progrape/router#12]
请问render能直接return一个URL吗？
看了API。貌似没有。
有没有一个好点的方法？

**Comment by progrape** [comment]
渲染页面是返回字符串的，可以同步或异步。什么样的场景是返回一个 URL ？希望渲染这个 url 的内容？

**Comment by zx8887** [comment]
@progrape 对的。就是能不能直接渲染url对应的内容。

**Comment by progrape** [comment]
这个需求不合理

**Comment by zx8887** [comment]
@progrape 那怎么才能通过url渲染页面。。。要是比较复杂的页面。字符串好麻烦哟。。

**Comment by progrape** [comment]
你可以用模板引擎来渲染页面，字符串塞进去；也可以异步去加载一个 url 得到内容，然后回调传递下去。

``` javascript
render: function (callback){
    $.get('/path/to/html').success(function(html){
        callback(null, html);
    });
}
```

**Comment by zx8887** [comment]
thk...
