### ISSUE TITLE
为什么官方演示的Demo有左右滑动的动画效果，而我的却没有咧

### ISSUE THREAD

**Issue by cgfeel** [progrape/router#13]
我和官方演示一样，用的是https://github.com/progrape/router.git 做路由的，为何官方点击页面切换的时候是有左右滑动的效果，而我没有呢？

我用起来很卡顿。。。。。

**Comment by progrape** [comment]
切换效果是 css 动画完成的，参考一下 example 的代码

**Comment by cgfeel** [comment]
已看到，谢谢
