### ISSUE TITLE
dist下能否提供一份无压缩版本呢？

### ISSUE THREAD

**Issue by cipchk** [progrape/router#2]

**Comment by progrape** [comment]
@cipchk 源码是 ES6 写的，是通过 babel 编成 ES5，编出来的版本就算不压缩也很难阅读。如果要阅读，建议直接阅读源码。

如果需要未压缩版，编译的时候把压缩插件去掉就行了。

https://github.com/progrape/router/blob/master/webpack.prod.config.js#L23

**Comment by cipchk** [comment]
@progrape 了解，谢谢
