### ISSUE TITLE
点击浏览器返回按钮后，数据变重复

### ISSUE THREAD

**Issue by sutra** [progrape/router#21]
复现方法：
Step 1. 使用浏览器（Chrome on Mac, Safari on Mac, Safari on iOS) 打开 https://github.com/progrape/router
Step 2. 点击预览那里的链接 https://progrape.github.io/router
Step 3. 等待画面加载完成后，点击浏览器的返回按钮，此时会看到画面的数据块重复，每点击一次，多出一块数据。除非你快速点击两次返回按钮（仅Mac）。
（实际上，你点击该 issue 里 Step 2 那里的链接也有同样的效果）

**Comment by progrape** [comment]
是个缺陷，页面一进入的时候，读取了 `setDefault` 设置的默认 url，然后设置 hash，就产生了历史记录，然后就可以后退

**Comment by baixiaosh** [comment]
这个问题怎么解决呢

**Comment by chux0519** [comment]
问题出在 src/index.js 的 44行 

```
 window.addEventListener('hashchange', (event) => {
        const hash = util.getHash(event.newURL);
        const state = history.state || {};

        this.go(hash, state._index <= this._index);
    }, false);
```

在执行 \* this.go \*  之前检验一下新旧hash是否相等就行了，如果相同，说明到达根路由了，直接return即可，因此可以改成这样：

```
    window.addEventListener('hashchange', (event) => {
        const old_hash = util.getHash(event.oldURL);
        const hash = util.getHash(event.newURL);
        // fix '/' repeat see https://github.com/progrape/router/issues/21
        if(old_hash === hash) return;   
        const state = history.state || {};

        this.go(hash, state._index <= this._index);
    }, false);
```

pr已经发了，也可以看这里
https://github.com/chux0519/router
