### ISSUE TITLE
bind 执行两次

### ISSUE THREAD

**Issue by havefive** [progrape/router#23]
手机端首次访问，bind执行两次,如下，会alert两次。

 var index = {
        url: '/',
        className: 'home',
        render: function (){
            return '<span>home</span>';
        },bind: function () {
           alert(1);
       }
}

**Comment by cgfeel** [comment]
一样的问题，如果是event的话，我一般都先off一下

```
$(elem).off().on()
```

我猜测，应该是在绑定事件的时候，给`<script type="text/template">`中的元素绑定了事件，当二次、三次加载的时候，事件就重复了。

所以希望作者在销毁的时候，麻烦把事件也同时销毁，谢谢

**Comment by cgfeel** [comment]
作者不更新了么。。。

**Comment by cgfeel** [comment]
我找到一个解决的办法，render中setTimeout你要执行的函数，就不会重复2次了
