### ISSUE TITLE
render重复问题

### ISSUE THREAD

**Issue by liuwei0514** [progrape/router#27]
页面间切换 ，快速返回多次会出现上个页面没有卸载  同时出现两个页面
console 报错
router.min.js:formatted:142Uncaught TypeError: Cannot read property 'removeChild' of null

**Comment by cgfeel** [comment]
我以前遇到过，要把所有js写到$(function() {})中就能解决问题了。

**Comment by liuwei0514** [comment]
我试试，谢谢

**Comment by liuwei0514** [comment]
//remove all child brfore appendChild new node by leslieliu 
                while (this._$container.firstChild) {
                    this._$container.removeChild(this._$container.firstChild);
                }
                this._$container.appendChild(node);
我修改了源码  貌似解决了
