### ISSUE TITLE
请问有主动触发路由更改的方法吗？

### ISSUE THREAD

**Issue by lukedesu** [progrape/router#3]
想在程序中定向到某个页面，
比如类似 router.trigger(/question/3")

目前有类似的方法可以用吗？

谢谢~

**Comment by progrape** [comment]
@senseluo 你好，最直接的方式就是设置 hash，`location.hash = '#/question/3'` ，或者调用 里面的 go 方法，https://github.com/progrape/router/blob/master/src/index.js#L96 ，`router.go('/question/3')` 也行；

如果是返回上一页，可以这样：`history.go(-1)`。路由会监听到 hash 的变化然后调转到对应的页面的。

**Comment by 270556660** [comment]
router.go('/question/3')绑定在bind里面会报错，是不持下面写法吗
var toast = {
        url: '/toast',
        className: 'toast',
        render: function() {
            return $('#tpl_toast').html();
        },bind: function() {
                       router.go('/button')
               }
    };
