### ISSUE TITLE
render 能支持ajax调用数据，再解析模板吗

### ISSUE THREAD

**Issue by wanjikun3** [progrape/router#4]
render 能支持ajax调用数据，再解析模板吗，特别针对带参数的，调用ajax返回的的数据绑定模板

**Comment by zouzhenxing** [comment]
https://github.com/zouzhenxing/router.git
修改index.js的init方法
`init() {
        window.addEventListener('hashchange', (event) => {
            const hash = util.getHash(event.newURL);
            const state = history.state || {};

```
        const route = this._getRoute(hash);
        let that = this;
        if( route && route.ajaxData ) {
            route.ajaxData().done(function(){
                that.go(route ? hash : that._default, state._index <= that._index);
            });
        } else {
            this.go(hash, state._index <= this._index);
        }
    }, false);

    if (history.state && history.state._index) {
        this._index = history.state._index;
    }

    this._index--;

    const hash = util.getHash(location.href);
    const route = this._getRoute(hash);
    let that = this;
    if( route && route.ajaxData ) {
        route.ajaxData().done(function(){
            that.go(route ? hash : that._default, state._index <= that._index);
        });
    } else {
        this.go(route ? hash : this._default);
    }

    return this;
}`
```

`var adminList = {
        url : "/adminList",
        className :  "adminList",
        ajaxData : function() {
            var that = this;
            return $._ajax({
                url  : "/admin/adminList",
                type : "get"
            }).done(function( data ) {
                that.data = data;
            });
        },
        render : function() {
            return ejs.render($("#adminList").html(),{admins:this.data});
        }
    }`
基于jquery返回一个deferred对象

**Comment by progrape** [comment]
新的提交可以ajax加载数据了
